name: color_extractor
description: "A Flutter package for extracting dominant colors from images using c with ffi for performance optimisation and multiple image formats support."
version: 0.0.1
homepage: https://github.com/hurbes/color_extractor

environment:
  sdk: ^3.5.3
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  camerawesome: ^2.1.0
  http: ^1.2.2
  logger: ^2.4.0
  image: ^4.3.0

dev_dependencies:
  ffi: ^2.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true